<a href="https://colab.research.google.com/github/marwamohamed51/Python_colab/blob/main/PythonTask_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
"""(1)
Load the HR attrition dataset and extract one numeric column only
(MonthlyIncome) into a NumPy array. Print the array.
"""

hr=pd.read_excel('/content/Hr dataset.xlsx')
hr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2925 entries, 0 to 2924
Data columns (total 39 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   Attrition                   2925 non-null   object 
 1   Business Travel             2925 non-null   object 
 2   CF_age band                 2925 non-null   object 
 3   CF_attrition label          2925 non-null   object 
 4   Department                  2925 non-null   object 
 5   Education Field             2925 non-null   object 
 6   emp no                      2925 non-null   object 
 7   Employee Number             2924 non-null   float64
 8   Gender                      2925 non-null   object 
 9   Job Role                    2925 non-null   object 
 10  Marital Status              2925 non-null   object 
 11  Over Time                   2925 non-null   object 
 12  Over18                      2925 non-null   object 
 13  Training Times Last Year    2925 

In [9]:
MonthlyIncome=np.array(hr['Monthly Income'])
print(MonthlyIncome)

[5993 5130 2090 ... 2275 2275 2275]


In [10]:
"""(2)
Print the data type (dtype) of the MonthlyIncome array.
"""

MonthlyIncome.dtype

dtype('int64')

In [15]:
"""(3)
Convert the MonthlyIncome values into a Python list and print both the
list and the NumPy array. Write one sentence describing the difference
you notice.
"""

MonthlyIncome_list=list(MonthlyIncome)
print("List")
print(MonthlyIncome_list)
print('\n')
print("Numpy Array")
print(MonthlyIncome)
print('\n')
print('The Difference is list output object values but numpy array output is values')

List
[np.int64(5993), np.int64(5130), np.int64(2090), np.int64(2909), np.int64(3468), np.int64(3068), np.int64(2670), np.int64(2693), np.int64(9526), np.int64(5237), np.int64(2426), np.int64(4193), np.int64(2911), np.int64(2661), np.int64(2028), np.int64(9980), np.int64(3298), np.int64(2935), np.int64(15427), np.int64(3944), np.int64(4011), np.int64(3407), np.int64(11994), np.int64(1232), np.int64(2960), np.int64(19094), np.int64(3919), np.int64(6825), np.int64(10248), np.int64(18947), np.int64(2496), np.int64(6465), np.int64(2206), np.int64(2086), np.int64(2293), np.int64(2645), np.int64(2683), np.int64(2014), np.int64(3419), np.int64(5376), np.int64(1951), np.int64(2341), np.int64(2293), np.int64(8726), np.int64(4011), np.int64(19545), np.int64(4568), np.int64(3022), np.int64(5772), np.int64(2269), np.int64(5381), np.int64(3441), np.int64(5454), np.int64(9884), np.int64(4157), np.int64(13458), np.int64(9069), np.int64(4014), np.int64(5915), np.int64(5993), np.int64(6162), np.int64(24

In [29]:
"""(4)
Calculate the total MonthlyIncome using:
--Python built-in sum() on the list
--NumPy np.sum() on the array
"""

print(f"Sum of MonthlyIncome_list : {sum(MonthlyIncome_list)}")
print(f"Sum of MonthlyIncome_array : {MonthlyIncome.sum()}")

Sum of MonthlyIncome_list : 19052887
Sum of MonthlyIncome_array : 19052887


In [41]:
"""(5)
Calculate the average MonthlyIncome using NumPy
"""

Avg=MonthlyIncome.mean()
print(f"Avg of MonthlyIncome : {Avg}")
print(f"Avg of MonthlyIncome : {round(Avg)}")

Avg of MonthlyIncome : 6513.807521367521
Avg of MonthlyIncome : 6514


In [55]:
"""(6)
Using simple indexing, print:
--The first 5 MonthlyIncome values
--The last 5 MonthlyIncome values
"""

print(f"The first 5 MonthlyIncome values : {MonthlyIncome[:5]}")
print(f"The last 5 MonthlyIncome values : {MonthlyIncome[-5:]}")

The first 5 MonthlyIncome values : [5993 5130 2090 2909 3468]
The last 5 MonthlyIncome values : [4581 2472 2275 2275 2275]


In [56]:
"""(7)
Find the highest and lowest MonthlyIncome using NumPy functions.
"""

print(f"Highest MonthlyIncome value : {MonthlyIncome.max()}")
print(f"Lowest MonthlyIncome value : {MonthlyIncome.min()}")

Highest MonthlyIncome value : 19999
Lowest MonthlyIncome value : 1009


In [62]:
"""(8)
Increase all MonthlyIncome values by 10% using NumPy and print the
new values.
"""

MonthlyIncome_10_percent = MonthlyIncome * 1.1
print(f"MonthlyIncome_10 : {MonthlyIncome_10_percent}")

MonthlyIncome_10 : [6592.3 5643.  2299.  ... 2502.5 2502.5 2502.5]


In [65]:
#another way
hr['10_percent']=MonthlyIncome + MonthlyIncome*10/100
print(hr['10_percent'])

0       6592.3
1       5643.0
2       2299.0
3       3199.9
4       3814.8
         ...  
2920    5039.1
2921    2719.2
2922    2502.5
2923    2502.5
2924    2502.5
Name: 10_percent, Length: 2925, dtype: float64


In [67]:
"""(9)
Count how many employees have MonthlyIncome greater than 5000
using NumPy conditions
"""

print(f"Employees have MonthlyIncome > 5000 : {np.sum(MonthlyIncome>5000)}")

Employees have MonthlyIncome > 5000 : 1437


In [73]:
"""(10)
Load one more numeric column (Age) into a NumPy array and print it.
"""

#Age=np.array(hr['Age'])
Age = np.array(hr.Age)
print(Age)

[41 49 37 ... 23 23 23]


In [75]:
"""(11)
Calculate the average Age using NumPy.
"""

avg_age=Age.mean()
print(f"Avg of Age : {round(avg_age)}")

Avg of Age : 37


In [78]:
"""(12)
Combine Age and MonthlyIncome into one NumPy array and print its
shape.
"""

combine=np.array([Age,MonthlyIncome])
print(combine)
print(f"The of combine between Age and Monthly Income: {combine.shape}")

[[  41   49   37 ...   23   23   23]
 [5993 5130 2090 ... 2275 2275 2275]]
The of combine between Age and Monthly Income: (2, 2925)


In [80]:
""" (13)
Print how many rows and how many columns the combined array has
"""

num_rows, num_cols = combine.shape
print(f"The combined array has {num_rows} rows and {num_cols} columns")

The combined array has 2 rows and 2925 columns
